#!/bin/sh
#
# libiscsi_fingerprint.sh — the shape of a kernel's libiscsi TMF declarations,
# as one hash, for the LU-reset fence's audited-kernel admission
#
# Usage: pal/linux/libiscsi_fingerprint.sh <path to include/scsi/libiscsi.h>
#   Prints a C header on stdout defining MXFS_LIBISCSI_FP.  Kbuild runs it
#   against the headers of the kernel being built, so the module carries the
#   shape of the kernel it was compiled for; run by hand against the read
#   reference tree (/src/linux) it yields the value dlm/scsipr.c admits.
#
# What is hashed, and nothing else: the enum that declares TMF_INITIAL, and the
# members of struct iscsi_session the one-TMF-per-session serialization is
# built from (eh_mutex, ehwait, tmhdr, tmf_timer, tmf_state, lu_reset_timeout,
# frwd_lock, back_lock) — comments removed, whitespace collapsed.  Two headers
# whose TMF declarations are identical hash identically whatever else in the
# file changed (6.17.2-1-pve differs from 7.1.0-rc7 only in the return type of
# iscsi_queuecommand).
#
# This is a STRUCTURAL fingerprint.  Declarations unchanged is evidence about
# the state machine the bodies are built from; it is not a reading of the
# bodies, and dlm/scsipr.c says so wherever it admits a kernel by it.
#
# It never fails a build: a missing header or an unrecognised shape defines
# MXFS_LIBISCSI_FP as "absent:<reason>", which no admission table contains, so
# the LU-reset fence is refused on that kernel and everything else builds.
#
hdr="$1"

emit() {
    echo "/* generated by pal/linux/libiscsi_fingerprint.sh from $hdr */"
    echo "#define MXFS_LIBISCSI_FP \"$1\""
}

if [ -z "$hdr" ] || [ ! -r "$hdr" ]; then
    emit "absent:no-header"
    exit 0
fi

# Comments out (block and line), then one declaration per line, whitespace
# collapsed, blank lines dropped.
clean=$(sed -e ':a' -e 's|/\*[^*]*\*\+\([^/*][^*]*\*\+\)*/||g' -e '/\/\*/{N;ba}' "$hdr" |
        sed -e 's|//.*$||' -e 's/[[:space:]]\+/ /g' -e 's/^ //' -e 's/ $//' |
        grep -v '^$')

enum=$(printf '%s\n' "$clean" | awk '
    /^enum[ {]/ { inb = 1; blk = "" }
    inb { blk = blk $0 "\n" }
    inb && /};/ { inb = 0; if (blk ~ /TMF_INITIAL/) printf "%s", blk }')

members=$(printf '%s\n' "$clean" | awk '
    /^struct iscsi_session \{/ { ins = 1; next }
    ins && /^};/ { ins = 0 }
    ins && /(^|[^A-Za-z0-9_])(eh_mutex|ehwait|tmhdr|tmf_timer|tmf_state|lu_reset_timeout|frwd_lock|back_lock)([^A-Za-z0-9_]|$)/ { print }')

nmem=$(printf '%s\n' "$members" | grep -c .)
if ! printf '%s' "$enum" | grep -q TMF_INITIAL; then
    emit "absent:no-tmf-enum"
    exit 0
fi
if [ "$nmem" -ne 8 ]; then
    emit "absent:iscsi_session-has-$nmem-of-8-members"
    exit 0
fi

fp=$(printf '%s\n%s\n' "$enum" "$members" | sha256sum | cut -c1-64)
emit "$fp"
