/* generated by pal/linux/libiscsi_fingerprint.sh from /usr/src/linux-headers-6.8.0-101-generic/include/scsi/libiscsi.h */
#define MXFS_LIBISCSI_FP "d5ee9d1ecdea95baf6f96d4321cab4c9fce04c32854e8ed646e58bec9598c3a1"
